---

global:
  scrape_interval:     30s
  evaluation_interval: 30s
  external_labels:
    monitor: 'm0n1t0r'

scrape_configs:
  - job_name: 'sensor'
    static_configs:
      - targets:
        - pi1:9113